import asyncio
import glob
import logging
import os
import re
import shutil
from pathlib import Path
from typing import Dict, Any, List, Optional

import crud
import database
import schema
import utils
from web import config

logger = logging.getLogger("web.downloader")

# Active download locks per (format_type, song_id/url) to avoid duplicate concurrent gamdl processes
_download_locks: Dict[str, asyncio.Lock] = {}
_global_lock = asyncio.Lock()


async def get_download_lock(key: str) -> asyncio.Lock:
    async with _global_lock:
        if key not in _download_locks:
            _download_locks[key] = asyncio.Lock()
        return _download_locks[key]


def get_codec_args(format_type: str) -> List[str]:
    fmt = format_type.lower()
    if fmt == "aac":
        return ["--song-codec-priority", "aac-web"]
    elif fmt == "atmos":
        return ["--song-codec-priority", "atmos"]
    elif fmt in ("mv", "video"):
        return ["--post-download-mode", "mv-mux"]
    else:  # alac (default)
        return []


def get_target_subfolder(format_type: str) -> str:
    fmt = format_type.lower()
    if fmt in ("aac", "atmos", "mv", "video", "alac"):
        return fmt if fmt != "video" else "mv"
    return "alac"


async def download_track_web(url: str, format_type: str = "alac") -> Dict[str, Any]:
    """
    Downloads an Apple Music track or album using gamdl directly to the local storage directory (./downloads).
    Indexes downloaded files into PostgreSQL database using shared CRUD functions.
    """
    format_type = format_type.lower()
    target_subfolder = get_target_subfolder(format_type)
    lock_key = f"{format_type}:{url}"
    lock = await get_download_lock(lock_key)

    async with lock:
        # Determine temporary workspace
        timestamp = int(asyncio.get_event_loop().time() * 1000)
        temp_dir = config.LOCAL_STORAGE_DIR / "temp" / f"web_{timestamp}"
        output_dir = temp_dir / "out"
        temp_dir.mkdir(parents=True, exist_ok=True)
        output_dir.mkdir(parents=True, exist_ok=True)

        cookies_file = config.BASE_DIR / "cookies.txt"
        cookies_arg = ["--cookies-path", str(cookies_file)] if cookies_file.exists() else []

        cmd = [
            "gamdl",
            "-n",
            *cookies_arg,
            "--output-path", str(output_dir),
            "--temp-path", str(temp_dir),
            *get_codec_args(format_type),
            url
        ]

        logger.info(f"[Web Downloader] Executing: {' '.join(cmd)}")

        process = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )

        stdout, _ = await process.communicate()
        output_log = stdout.decode("utf-8", errors="ignore") if stdout else ""
        logger.info(f"[Web Downloader] Process finished with exit code {process.returncode}")

        # Scan for output files
        extensions = ["*.m4a", "*.mp4", "*.caf"]
        downloaded_files = []
        for ext in extensions:
            downloaded_files.extend(glob.glob(os.path.join(str(output_dir), "**", ext), recursive=True))

        valid_files = []
        for fp in downloaded_files:
            norm = fp.replace("\\", "/")
            fname = os.path.basename(norm)
            if "gamdl_temp" in norm or "_temp" in norm or fname.endswith("_encrypted.m4a") or fname.endswith(".tmp"):
                continue
            valid_files.append(fp)

        if not valid_files:
            # Clean temp directory
            shutil.rmtree(temp_dir, ignore_errors=True)
            return {
                "success": False,
                "error": "No media files were generated by gamdl. Requested format might be unavailable or URL invalid.",
                "log": output_log[-1000:] if output_log else ""
            }

        dest_folder = config.LOCAL_STORAGE_DIR / target_subfolder
        dest_folder.mkdir(parents=True, exist_ok=True)

        results = []
        for file_path in valid_files:
            fname = os.path.basename(file_path)
            dest_path = dest_folder / fname

            # Move file to permanent storage folder
            shutil.move(file_path, dest_path)

            # Parse metadata using mutagen (utils.py)
            metadata = utils.get_track_metadata(str(dest_path))
            file_size = os.path.getsize(dest_path)

            title = metadata.get("title") or Path(fname).stem
            artist = metadata.get("artist") or "Unknown Artist"
            album = metadata.get("album") or "Unknown Album"
            isrc = metadata.get("isrc") or ""

            # Standardize song_id from URL or filename
            song_id_match = re.search(r"i=(\d+)|/song/(?:[^/]+/)?(\d+)", url)
            song_id = song_id_match.group(1) or song_id_match.group(2) if song_id_match else isrc or str(timestamp)

            # Insert/Update PostgreSQL database record
            track_schema = schema.TrackInputSchema(
                song_id=song_id,
                title=title,
                artist=artist,
                album=album,
                isrc=isrc,
                url=url,
                chat_id=0,
                message_id=None,
                file_id="",
                artwork="",
                size=file_size
            )

            async with database.async_session() as session:
                if format_type == "aac":
                    await crud.create_aac_track(session, track_schema)
                elif format_type == "atmos":
                    await crud.create_atmos_track(session, track_schema)
                elif format_type in ("mv", "video"):
                    await crud.create_mv_track(session, track_schema)
                else:
                    await crud.create_track(session, track_schema)

            results.append({
                "song_id": song_id,
                "title": title,
                "artist": artist,
                "album": album,
                "format": target_subfolder,
                "filename": fname,
                "size": file_size,
                "file_path": str(dest_path),
                "download_url": f"/download/{target_subfolder}/{song_id}",
                "stream_url": f"/stream/{target_subfolder}/{song_id}"
            })

        # Cleanup temp workspace
        shutil.rmtree(temp_dir, ignore_errors=True)

        return {
            "success": True,
            "count": len(results),
            "tracks": results
        }
